---
- name: Copy the template
  copy:
    src: "{{ template_source_path }}"
    dest: "{{ weblogic_template }}"

- name: unpack the weblogic domain
  shell: "{{ weblogic_unpack_path }}/unpack.sh -template={{ weblogic_template }} -domain={{ weblogic_domain }}"
  become: yes
  become_user: "{{ oracle_weblogic_user }}"
